### PR TITLE
Migrate deprecated lifecycle props

### PR DESCRIPTION
**Pull request by EvHaus**
The latest version of React deprecates componentWillReceiveProps and componentWillMount. These changes should address that.

### CODE REVIEW

**Review by Tsourdox — COMMENTED** [review]
Epic 👍

**Comment by meriadec** [comment]
Thanks @EvHaus and sorry for the delay :D notification was lost in the past..
I'm facing issue on your patch, the Modal don't show up anymore, can you check on your side if it's working?

open

**Comment by EvHaus** [comment]
@meriadec Can you double check what version of React you've got installed there?

**Comment by meriadec** [comment]
The one that is inside package.json

**Comment by meriadec** [comment]
Feel free to bump it along with your PR, it's been a long time :D

**Comment by EvHaus** [comment]
I'll take a look this evening.

**Comment by EvHaus** [comment]
Pushed the fix. It was because `react` and `react-dom` needs to be upgraded to 16.3.0+.

I also opened another MR to upgrade the other dependencies too for you here: https://github.com/meriadec/react-mortal/pull/8

**Comment by meriadec** [comment]
Thanks @EvHaus

**Comment by meriadec** [comment]
just published 3.3.0 on npm

**Pull request merged**
